name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install compiler
      run: |
        sudo apt install mingw-w64
        rustup target add x86_64-pc-windows-gnu
      
    - name: Build for Windows
      run: |
        cd pdb2seq
        cargo build --target=x86_64-pc-windows-gnu --release

    - name: Upload Windows zip
      uses: actions/upload-artifact@v3    
      with:
        name: pdb2seq for windows
        path: ./pdb2seq/release/pdb2seq.exe

    - name: Build for Linux
      run: |
        cd pdb2seq
        cargo build --release

    - name: Upload Windows zip
      uses: actions/upload-artifact@v3    
      with:
        name: pdb2seq for Linux
        path: ./pdb2seq/release/pdb2seq
      

    
