name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install compiler
      run: rustup target add x86_64-pc-windows-gnu
      
    - name: Build
      run: |
        cd pdb2seq
        cargo build --target=x86_64-pc-windows-gnu --release

    
